#define P9_21 0x44e10954 			// 0B subsystem 
#define P9_16 0x44e1084C			// 1B subsystem
#define P8_13 0x44e10824			// 2B subsystem 

#define SOC_EPWM_REGS (0x00000200)

#define SOC_PWMSS0_REGS (0x48300000)
#define SOC_EPWM_0_REGS (SOC_PWMSS0_REGS + SOC_EPWM_REGS)

#define SOC_PWMSS1_REGS (0x48302000)
#define SOC_EPWM_1_REGS (SOC_PWMSS1_REGS + SOC_EPWM_REGS)

#define SOC_PWMSS2_REGS (0x48304000)
#define SOC_EPWM_2_REGS (SOC_PWMSS2_REGS + SOC_EPWM_REGS)

#define EHRPWM_TBPRD (0xA)
#define EHRPWM_TBCTL (0x0)
#define CMPA (0x12)
#define EHRPWM_TBCTL_PRDLD (0x0008u)
#define EHRPWM_TBCTL_CTRMODE (0x0003u)
#define EHRPWM_PRD_LOAD_SHADOW_MASK EHRPWM_TBCTL_PRDLD
#define EHRPWM_TBCTL_PRDLD_SHIFT (0x0003u)
#define EHRPWM_TBCTL_CTRMODE_SHIFT (0x0000u)
#define EHRPWM_TBCTL_CTRMODE_UPDOWN (0x0002u)
#define EHRPWM_TBCTL_CTRMODE_UP (0x0000u)
#define EHRPWM_COUNTER_MODE_MASK EHRPWM_TBCTL_CTRMODE

#define EHRPWM_TBCTL_HSPCLKDIV_14 (0x000Eu)
#define EHRPWM_TBCTL_HSPCLKDIV_DIVBY1 (0x0000u)
#define EHRPWM_TBCTL_HSPCLKDIV_DIVBY14 (0x0007u)
#define EHRPWM_TBCTL (0x0)
#define EHRPWM_TBCTL_CLKDIV (0x1C00u)
#define EHRPWM_TBCTL_CLKDIV_SHIFT (0x000Au)
#define EHRPWM_TBCTL_HSPCLKDIV (0x0380u)
#define EHRPWM_TBCTL_HSPCLKDIV_SHIFT (0x0007u)

#define SOC_CONTROL_REGS (0x44E10000)
#define CONTROL_PWMSS_CTRL (0x664)
#define CONTROL_PWMSS_CTRL_PWMSS0_TBCLKEN (0x00000001u)
#define CONTROL_PWMSS_CTRL_PWMMS1_TBCLKEN (0x00000002u)
#define CONTROL_PWMSS_CTRL_PWMSS2_TBCLKEN (0x00000004u)

#define CPLD_CTRLREG_OFFSET 0x10
#define PWMSS_CLOCK_CONFIG 0x08
#define PWMSS_EHRPWM_CLK_EN_ACK 0x100
#define SOC_PRCM_REGS (0x44E00000)
#define EHRPWM_CMPCTL_OVERWR_SH_FL 0x1

#define EHRPWM_COMPA_NO_LOAD (EHRPWM_CMPCTL_LOADAMODE_FREEZE << EHRPWM_CMPCTL_LOADAMODE_SHIFT)

#define EHRPWM_CMPCTL (0xE)
#define EHRPWM_CMPCTL_SHDWAFULL (0x0100u)
#define EHRPWM_CMPCTL_SHDWAFULL_SHIFT (0x0008u)
#define EHRPWM_SHADOW_A_EMPTY (0x0 << EHRPWM_CMPCTL_SHDWAFULL_SHIFT)
#define EHRPWM_CMPCTL_SHDWAMODE (0x0010u)
#define EHRPWM_CMPCTL_SHDWAMODE_SHIFT (0x0004u)
#define EHRPWM_CMPCTL_LOADAMODE (0x0003u)
#define EHRPWM_COMPA_LOAD_MASK EHRPWM_CMPCTL_LOADAMODE
#define EHRPWM_CMPCTL_LOADAMODE_SHIFT (0x0000u)

#define EHRPWM_CMPA (0x12)
#define EHRPWM_CMPA_CMPA (0xFFFFu)

#define EHRPWM_COUNT_UP_DOWN (EHRPWM_TBCTL_CTRMODE_UPDOWN << EHRPWM_TBCTL_CTRMODE_SHIFT)
#define EHRPWM_COUNT_UP	(EHRPWM_TBCTL_CTRMODE_UP << EHRPWM_TBCTL_CTRMODE_SHIFT)
#define EHRPWM_SHADOW_WRITE_DISABLE 0x1

#define EHRPWM_AQCTLA (0x16)
#define EHRPWM_AQCTLB (0x18)
#define EHRPWM_AQSFRC (0x1A)
#define EHRPWM_AQCSFRC (0x1C)

#define CLOCK_DIV_VAL (10)
#define SOC_EHRPWM_2_MODULE_FREQ (1000000000)
#define CONTROL_CONF_GPMC_AD(n) (0x800 + (n * 4))
#define CONTROL_CONF_MUXMODE(n) (n)

#define HWREGH(x) (*((volatile unsigned short *)(x)))
#define HWREG(x) (*((volatile unsigned int *)(x)))


syscall pwm_init(int);
syscall pwm_write(int, uint8);
